---
title: Catequesis
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: minima
minima:
  date_format: "%d %b de %Y"
header_pages:
  - index.html
